[app]
stopTimeout = 10 # seconds

[logging] # root logger
level = "debug" # default: info
enableCaller = "error"
enableStack = "error"
handler = "stdout"

[serve.grpc]
host = "0.0.0.0"
port = 9000
maxConcurrentStreams = 3000
maxTcpConnections = 7000

[serve.gateway]
host = "0.0.0.0"
port = 9090
upstream = "127.0.0.1:9000"

[serve.http]
debug = true
host = "0.0.0.0"
port = 8080

[deps.etcd]
endpoints = []
dialTimeout = 3
readTimeout = 3
writeTimeout = 3

[deps.postgres]
host = "127.0.0.1"
port = 3306
db = ""
user = ""
password = ""
maxOpen = 300
maxIdle = 100
maxLife = 3600
migrate = true

[deps.redis]
address = "127.0.0.1:6379"
user = ""
password = ""
db = 0
maxRetries = 3
poolSize = 300
minIdle = 30

[deps.email]
host = ""
port = 587
from = ""
password = ""
template = ""